"""empty message

Revision ID: 075fed8db93b
Revises: 
Create Date: 2019-06-08 02:11:29.819659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075fed8db93b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isAlive', sa.Boolean(), nullable=True),
    sa.Column('placeId', sa.Integer(), nullable=False),
    sa.Column('isKing', sa.Boolean(), nullable=True, default=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peoples')
    # ### end Alembic commands ###
