"""empty message

Revision ID: 7e8c983db76b
Revises: 075fed8db93b
Create Date: 2019-11-19 18:03:12.887402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8c983db76b'
down_revision = '075fed8db93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peoples', 'placeId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peoples', 'placeId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
