"""empty message

Revision ID: 6062421774fe
Revises: 
Create Date: 2020-06-02 13:52:39.741828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6062421774fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False, comment='username'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='email'),
    sa.Column('first_name', sa.String(length=255), nullable=False, comment='first_name'),
    sa.Column('last_name', sa.String(length=255), nullable=False, comment='last_name'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='password'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
