apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: place-db
  name: place-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: place-db
  template:
    metadata:
      labels:
        app: place-db
    spec:
      containers:
      - image: postgres:9.4
        name: postgres
        env:
        - name: POSTGRES_USER
          value: place_user
        - name: POSTGRES_PASSWORD
          value: place_pass
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 