apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: place-db
  name: place-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: place-db
  template:
    metadata:
      labels:
        app: place-db
    spec:
      containers:
      - image: postgres:9.4
        name: postgres
        env:
        - name: POSTGRES_USER
          value: place_user
        - name: POSTGRES_PASSWORD
          value: place_pass
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: people-db
  name: people-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-db
  template:
    metadata:
      labels:
        app: people-db
    spec:
      containers:
      - image: postgres:9.4
        name: postgres
        env:
        - name: POSTGRES_USER
          value: people_user
        - name: POSTGRES_PASSWORD
          value: people_pass
        ports:
        - containerPort: 5433
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-db
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
      - image: postgres:9.4
        name: postgres
        env:
        - name: POSTGRES_USER
          value: users_user
        - name: POSTGRES_PASSWORD
          value: users_pass
        ports:
        - containerPort: 5434
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}