apiVersion: v1
kind: Service
metadata:
  labels:
    app: place-db
  name: place-db
spec:
  type: ClusterIP
  ports:
  - name: "place-db"
    port: 5432
    targetPort: 5432
  selector:
    app: place-db

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: people-db
  name: people-db
spec:
  type: ClusterIP
  ports:
  - name: "people-db"
    port: 5433
    targetPort: 5432
  selector:
    app: people-db

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: users-db
  name: users-db
spec:
  type: ClusterIP
  ports:
  - name: "users-db"
    port: 5434
    targetPort: 5432
  selector:
    app: users-db