apiVersion: v1
kind: Service
metadata:
  labels:
    app: place-db
  name: place-db
spec:
  type: ClusterIP
  ports:
  - name: "place-db"
    port: 5432
    targetPort: 5432
  selector:
    app: place-db