
apiVersion: v1
kind: Service
metadata:
  labels:
    app: got
  name: got
spec:
  type: NodePort
  ports:
  - name: "got"
    port: 5000
    nodePort: 31000
  selector:
    app: got
  

apiVersion: v1
kind: Service
metadata:
  labels:
    app: place
  name: place
spec:
  type: NodePort
  ports:
  - name: "place-service"
    port: 5000
    targetPort: 80
    nodePort: 31010
  selector:
    app: place
  

apiVersion: v1
kind: Service
metadata:
  labels:
    app: people
  name: people
  namespace: people
spec:
  type: NodePort
  ports:
  - name: "people-service"
    port: 5000
    targetPort: 80
    nodePort: 31020
  selector:
    app: people